### ISSUE TITLE
Zoom auf lokalem Gerät

### ISSUE THREAD

**Issue by Lionsit** [Bettman66/ioBroker.wiobrowser#29]
Hallo, ist es möglich, den Zoom schon lokal auf dem Gerät einzustellen? Beispielsweise über die Config.ini? Vielen Dank vorab.

**Comment by Bettman66** [comment]
Ja,schau ich mir an.

**Comment by Bettman66** [comment]
Hier zum testen.
[TestBrowser](https://github.com/Bettman66/wiobrowser/raw/main/wioBrowser.7z)

**Comment by Lionsit** [comment]
Vielen Dank für die schnelle Umsetzung. Zoom funktioniert mit dem Testbrowser. Ich bekomme aber nach etwa 5 Sekunden eine Fehlermeldung:
![image](https://user-images.githubusercontent.com/93179429/173517938-8c376763-fc9d-44a0-a620-0aefa8e49a96.png)
 Weitere 5 Sekunden nach Bestätigung bekomme ich dann eine weitere Fehlermeldung :
![image](https://user-images.githubusercontent.com/93179429/173517817-cc111215-257a-46bd-af52-5692f23077b9.png)

Verwendet hatte ich Framework 97.1.5.0.

**Comment by Bettman66** [comment]
[Teste den mal.](https://github.com/Bettman66/wiobrowser/raw/main/wioChWeb.7z)
Hatte oben einen neuen Compiler genutzt, die wurde wieder mit dem alten übersetzt.

**Comment by Lionsit** [comment]
Funktioniert, Danke!
