### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Sundancer78** [Bettman66/ioBroker.wiobrowser#67]
Hi,

ich starte den WioBrowser per Autostart. Seit 2 oder 3 Tagen kommt die Fehlermeldung "Permission denied ('10013 in listen:Bind).
Im Task Manager erscheinen mehrere Instanzen unter Prozesse, der Task wioBrowser lässt sich auch nicht beenden. 
An den Einstellungen im wioBrowser wurde nichts verändert, normalerweise minimiere ich den wioBrowser einfach wenn er geladen wurde.

![wiobrowser](https://github.com/Bettman66/ioBroker.wiobrowser/assets/42901216/d22105ba-9f76-49ca-8e4e-432dc68e4cec)
![wiobrowser_task-M](https://github.com/Bettman66/ioBroker.wiobrowser/assets/42901216/07b8ed59-8136-40bd-9db4-c0d50d25353a)

**Comment by Bettman66** [comment]
Das kommt wenn der wioBrowser mehr wie einmal gestartet wurde.
Ich schau mal ob ich eine Sperre für Mehrfachstart einbauen kann.

**Comment by Bettman66** [comment]
Hier zum testen, wioBrowser wird nur einmal gestartet.
[wioBrowser OneInstance](https://github.com/Bettman66/wiobrowser/raw/main/wio.zip)

**Comment by Sundancer78** [comment]
Hi,
bei mir kommt immer noch die Fehlermeldung. Habe wiorowser aus dem Autostart rau genommen, neu getartet, im Taskmanger kein wioBrowser zu finden. Manuell gestartet und wieder Permission denied.

**Comment by Bettman66** [comment]
Ich konnte die Meldung nur durch einen Doppelstart reproduzieren. Versuche mal in der wiobrowser.ini den Port zu ändern evtl. wird er von einem anderen Programm belegt.

**Comment by Sundancer78** [comment]
es lag tatsächlich am Port, hab ihn geändert und nun geht wieder alles. Danke
